---
# tasks file for ericsysmin.logrotate

- name: Logrotate | Install logrotate
  package: name=logrotate
  when: logrotate_install

- name: Logrotate | Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ item.name }}"
  with_items: "{{ logrotate_files }}"
  when: logrotate_files is defined
