---
- name: Converge
  hosts: all
  roles:
    - role: ericsysmin.logrotate
      logrotate_files:
        - name: rails
          path: "/var/log/service_logs"
          options:
            - weekly
            - size 25M
            - missingok
            - compress
            - delaycompress
            - copytruncate
